// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIETpVpGJeWzrmuONHHxrUSc70qbaB0rQ',
    appId: '1:1095576233465:web:7a3c702808718bb0104928',
    messagingSenderId: '1095576233465',
    projectId: 'comeback-1f112',
    authDomain: 'comeback-1f112.firebaseapp.com',
    storageBucket: 'comeback-1f112.firebasestorage.app',
    measurementId: 'G-7XXYD2J3VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtDFuI_nLrprPD9aQwamTJpOtWV40Rfcw',
    appId: '1:1095576233465:android:2dc730186d36f3c6104928',
    messagingSenderId: '1095576233465',
    projectId: 'comeback-1f112',
    storageBucket: 'comeback-1f112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbHOBeRBoTgaEZ1t6CyproBHPe01wrSw',
    appId: '1:1095576233465:ios:287a07065830350c104928',
    messagingSenderId: '1095576233465',
    projectId: 'comeback-1f112',
    storageBucket: 'comeback-1f112.firebasestorage.app',
    iosBundleId: 'com.example.comeback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdbHOBeRBoTgaEZ1t6CyproBHPe01wrSw',
    appId: '1:1095576233465:ios:ea96203bc3525de5104928',
    messagingSenderId: '1095576233465',
    projectId: 'comeback-1f112',
    storageBucket: 'comeback-1f112.firebasestorage.app',
    iosBundleId: 'com.example.comeBack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIETpVpGJeWzrmuONHHxrUSc70qbaB0rQ',
    appId: '1:1095576233465:web:fd47d4d16f05ef74104928',
    messagingSenderId: '1095576233465',
    projectId: 'comeback-1f112',
    authDomain: 'comeback-1f112.firebaseapp.com',
    storageBucket: 'comeback-1f112.firebasestorage.app',
    measurementId: 'G-K6L6H3ZN6E',
  );

}